### ISSUE TITLE
Firefox Port

### ISSUE THREAD

**Issue by trevorraney** [stevedecoded/youtube-upload-date#2]
This isn't an issue, your extension is exactly what I've been looking for. However, I use Firefox, and not Chromium-based browsers. 

I ported your extension to Firefox, and after successfully testing locally I submitted to their add-on site. You can view it here: https://addons.mozilla.org/en-US/firefox/addon/show-youtube-upload-date/. 

Happy to transfer ownership to you. And thank you again for making this extension!

**Comment by stevedecoded** [comment]
Nice! It could be merged into this repo in the future but for now I've mentioned you and the add-on in the readme.

Would you like to make the code for it public in your GitHub and I'll link to that too?

**Comment by trevorraney** [comment]
Sure 😅 there is very little deviation from your original code. I think I just changed the manifest value so it works with Firefox. Will upload it to my Github when I get some free time.

**Comment by Sh4ftMaster** [comment]
Hi, I've noticed that the Firefox version doesn't work with the Return Youtube Dislike extension enabled. The dislike count pops up while the page is loading and then diappears as the upload date comes into view. The same doesn't occur in Brave.

**Comment by stevedecoded** [comment]
The Chrome version is compatible with Return YouTube Dislike so I assume a straight port of the latest code from this repo will do the job. Firefox extension is at version 2.5 and Chrome version is on 2.7. One for @trevorraney
