### ISSUE TITLE
YouTube have updated the video UI to show the upload date

### ISSUE THREAD

**Issue by stevedecoded** [stevedecoded/youtube-upload-date#3]
Not sure how many users now have this new UI but this extension will become less relevant over time as it rolls out.

Open to suggestions for other UI tweaks/fixes.

Otherwise it's been nice knowin' ya! 😎

<img width="812" alt="Screenshot 2022-08-10 at 21 55 00" src="https://user-images.githubusercontent.com/673850/184018533-c416ad63-4374-4b3e-9140-80611a0efc95.png">

**Comment by tuurep** [comment]
Oh. Thanks for the heads up, and for the plugin which has helped me out quite a bit!

**Comment by stevedecoded** [comment]
@tuurep Do you have YouTube’s new UI? It would be great if you could share a few things about your setup so I can better understand who gets it and who doesn’t.

* OS
* Browser
* Screen resolution
* Whether you use a guest/free/premium YouTube account

I take it from the fact the plugin still gets downloads and reviews that their new UI hasn’t rolled out for everyone.

**Comment by tuurep** [comment]
Yea no, if the UI update will have a split video description and small comment section like in the screenshot, I don't have it like that yet.

* Arch Linux
* Vivaldi
* 1920x1080
*  Free account (logged in)

I made sure to try with Firefox and Chrome as well and it's the exact same layout (not updated).

Yep in fact I didn't know this UI change was coming until I saw this issue, and very confusing to know why people get it months apart - some people in Reddit apparently already had that 4 months ago!

On topic of this plugin, I'll have to see if with the new UI the video date will be visible even when the browser window is very small (narrow in width) - that's exactly why I used this plugin to begin with. Maybe you can let me know if you got the UI update? :)

**Comment by tuurep** [comment]
Hi again, I got my UI updated just now. (2.9.2022 ~23:25)

I can answer my own question too

> I'll have to see if with the new UI the video date will be visible even when the browser window is very small (narrow in width)

Yes the new UI resolves this issue completely and no matter how narrow the window, viewcount & upload date can't get hidden.
