### ISSUE TITLE
Dates in Sidebar are incorrect

### ISSUE THREAD

**Issue by Caladude** [stevedecoded/youtube-upload-date#8]
Sidebar results use incorrect dates. I don't know where this data is being gotten from.

Note the date on this video (june 6th of this year??)
![image](https://github.com/stevedecoded/youtube-upload-date/assets/8147039/b3a797e8-691e-4376-8b8a-a61509d76f6d)

and when it was ACTUALLY uploaded. The description date is indeed correct. 
![image](https://github.com/stevedecoded/youtube-upload-date/assets/8147039/d4b500fc-4953-4d61-a3f7-2f0e744ca584)

**Comment by stevedecoded** [comment]
@Caladude if you could let me know the following it would help a lot with the fix:

- YouTube URL of the page with broken date
- OS (Windows/Mac/etc)
- Browser (Chrome/Safari/etc)
- Screen resolution http://whatismyscreenresolution.net/
- Whether your account is free/premium
- Whether you're logged in/out
- Screenshot of the whole page

**Comment by stevedecoded** [comment]
@TomiBelan Thanks for this, I've added your fix and a new version of the extension has been submitted for review and should be live soon (v3.3).
